# Site settings
title: array101
email: hello@array101.com
description: linux/ruby/rails stuff
permalink: /blog/:year/:title.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://array101.github.com" # the base hostname & protocol for your site
github_username:  array101

# Build settings
markdown: redcarpet

gems:
- jekyll-feed
