version: '3.9'

services:
    zola:
        build: .
        image: balthek/zola:0.13.0
        container_name: zola-localhost
        volumes:
            - .:/app
        ports:
            - 8080:8080
        # command: |
        #     serve --interface 0.0.0.0 --port 8080 --base-url localhost
